# Generated by Django 3.0.5 on 2020-04-10 18:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronJobs',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=20, unique=True)),
                ('job_description', models.TextField(default='No Description Provided')),
            ],
        ),
    ]
